### ISSUE TITLE
Export Match Data as a txt file

### ISSUE THREAD

**Issue by weshford** [yungztrunks/club-manager#1]
Exporting a match contents into a text file is currently not working. the program simply creates an empty file. normally it should work as I am flushing the code but im not sure any help would be appreciated

**Comment by yungztr** [comment]
Fixed with commit [#e0363f6](https://github.com/yungztr/club-manager/commit/e0363f62ec48965e9580a665e92f520009d70486)
forgot to add lol

**Comment by weshford** [comment]
Fixed with commit [#e0363f6](https://github.com/weshford/club-manager/commit/e0363f62ec48965e9580a665e92f520009d70486)
forgot to add lol
